### ISSUE TITLE
Unable to launch survey using event name or properties for targeted sampling

### ISSUE THREAD

**Issue by sg-dev-2020** [Wootric/WootricSDK-flutter#1]
Hi,
How can flutter sdk be used to launch survey based on targeted sampling? Currently, it opens only default survey.
Is there a way to launch survey based on event name or user properties like it does in Android? https://docs.wootric.com/android/#targeted-sampling

**Comment by diegoserranoa** [comment]
Hi @sg-dev-2020 currently it can working with properties but not with `event_name`. We're also working on adding that right now and we'll let you know once the update containing that functionality is released.

**Comment by vijayradke** [comment]
Hi @sg-dev-2020  Fixed this issue in version 0.0.4. Here is the plugin url - https://pub.dev/packages/wootricsdk_flutter
