### ISSUE TITLE
How to change ui of ces survey in the flutter app

### ISSUE THREAD

**Issue by sg-dev-2020** [Wootric/WootricSDK-flutter#2]
Does sdk provide any functionality to change the survey ui like change of font color and background color? Android sdk does provide it - https://docs.wootric.com/android/#color-customization-smartphones-only. 
Wondering if it is planned for flutter sdk as well in the future?

**Comment by diegoserranoa** [comment]
Hi @sg-dev-2020 we're currently working on adding these methods here! We'll let you know once they are available.

**Comment by vijayradke** [comment]
Hi @sg-dev-2020 Fixed this issue in version 0.0.4. Here is the plugin url - https://pub.dev/packages/wootricsdk_flutter
