### ISSUE TITLE
Version from master or 0.0.6 doesn't work on iOS 11 or higher

### ISSUE THREAD

**Issue by juarezfranco** [Wootric/WootricSDK-flutter#7]
When I run `pod install`

```red
[!] CocoaPods could not find compatible versions for pod "WootricSDK":
  In snapshot (Podfile.lock):
    WootricSDK (= 0.21.0)

  In Podfile:
    wootricsdk_flutter (from `.symlinks/plugins/wootricsdk_flutter/ios`) was resolved to 0.0.1, which depends on
      WootricSDK (= 0.25.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `WootricSDK` inside your development pod `wootricsdk_flutter`.
   You should run `pod update WootricSDK` to apply changes you've made.
```

I created a fork to resolve:
https://github.com/Wootric/WootricSDK-flutter/commit/9bfdb899dfc519378575de88cf02b284139c7177

I did a downgrade from 'WootricSDK', '0.25.0' to 'WootricSDK', '0.21.0' in `ios/wootricsdk_flutter.podspec`. It's work.

**Comment by diegoserranoa** [comment]
Hi @juarezfranco I checked this issue and the problem is that we stopped support for versions 11 and lower in the `WootricSDK` version 0.22.0 https://github.com/Wootric/WootricSDK-iOS/blob/master/CHANGELOG.md#0220-2022-09-01

**Comment by juarezfranco** [comment]
Ok, thanks.
